/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stock;

import java.awt.event.WindowEvent;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author jenz_
 */
public class EmployeeLogin extends javax.swing.JFrame {
    
    /**
     * Creates new form PurchaseItem2
     */
    public EmployeeLogin() {
        setTitle("Update Stock");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        employeeLoginUpperJPanel = new javax.swing.JPanel();
        loginTxtLbl = new javax.swing.JLabel();
        stockTxtLbl = new javax.swing.JLabel();
        updateTxtLbl = new javax.swing.JLabel();
        LogoLbl = new javax.swing.JLabel();
        employeeLoginLowerJPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        usernameLbl = new javax.swing.JLabel();
        passwordLbl = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();
        usernameTxtField = new javax.swing.JTextField();
        passwordTxtField = new javax.swing.JPasswordField();
        warningLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        employeeTxtLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gmarket");
        setBackground(new java.awt.Color(51, 204, 255));
        setIconImage(new ImageIcon(getClass().getResource("icon.gif")).getImage());
        setMinimumSize(new java.awt.Dimension(1300, 999));
        setSize(new java.awt.Dimension(900, 600));

        employeeLoginUpperJPanel.setBackground(new java.awt.Color(0, 153, 255));
        employeeLoginUpperJPanel.setLayout(null);

        loginTxtLbl.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        loginTxtLbl.setText("LOGIN");
        employeeLoginUpperJPanel.add(loginTxtLbl);
        loginTxtLbl.setBounds(590, 160, 130, 80);

        stockTxtLbl.setFont(new java.awt.Font("Harlow Solid Italic", 1, 48)); // NOI18N
        stockTxtLbl.setText(" Logistics");
        employeeLoginUpperJPanel.add(stockTxtLbl);
        stockTxtLbl.setBounds(480, 410, 220, 80);

        updateTxtLbl.setFont(new java.awt.Font("Harlow Solid Italic", 1, 48)); // NOI18N
        updateTxtLbl.setText("Warehouse &");
        employeeLoginUpperJPanel.add(updateTxtLbl);
        updateTxtLbl.setBounds(410, 340, 320, 90);

        LogoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/img/fork2.png"))); // NOI18N
        employeeLoginUpperJPanel.add(LogoLbl);
        LogoLbl.setBounds(580, 80, 555, 532);

        employeeLoginLowerJPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        usernameLbl.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        usernameLbl.setForeground(new java.awt.Color(255, 255, 255));
        usernameLbl.setText("USER ID:");

        passwordLbl.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        passwordLbl.setForeground(new java.awt.Color(255, 255, 255));
        passwordLbl.setText("PASSWORD:");

        exitBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        exitBtn.setText("EXIT");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        loginBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        loginBtn.setText("LOGIN");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        usernameTxtField.setText("type your user ID here...");
        usernameTxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameTxtFieldMouseClicked(evt);
            }
        });
        usernameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTxtFieldActionPerformed(evt);
            }
        });

        passwordTxtField.setText("jPasswordField1");
        passwordTxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordTxtFieldMouseClicked(evt);
            }
        });
        passwordTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtFieldActionPerformed(evt);
            }
        });

        warningLbl.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        warningLbl.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(warningLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addComponent(passwordTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                    .addComponent(usernameTxtField))
                .addGap(221, 221, 221))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLbl))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLbl))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warningLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        usernameLbl.getAccessibleContext().setAccessibleName("usernameLbl");
        passwordLbl.getAccessibleContext().setAccessibleName("passwordLbl");
        exitBtn.getAccessibleContext().setAccessibleName("exitBtn");
        loginBtn.getAccessibleContext().setAccessibleName("loginBtn");
        usernameTxtField.getAccessibleContext().setAccessibleName("usernameTxtField");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/img/Gmarket_2.png"))); // NOI18N

        javax.swing.GroupLayout employeeLoginLowerJPanelLayout = new javax.swing.GroupLayout(employeeLoginLowerJPanel);
        employeeLoginLowerJPanel.setLayout(employeeLoginLowerJPanelLayout);
        employeeLoginLowerJPanelLayout.setHorizontalGroup(
            employeeLoginLowerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeLoginLowerJPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        employeeLoginLowerJPanelLayout.setVerticalGroup(
            employeeLoginLowerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeLoginLowerJPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        employeeLoginUpperJPanel.add(employeeLoginLowerJPanel);
        employeeLoginLowerJPanel.setBounds(0, 632, 1336, 310);

        employeeTxtLbl.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        employeeTxtLbl.setText("EMPLOYEE");
        employeeLoginUpperJPanel.add(employeeTxtLbl);
        employeeTxtLbl.setBounds(590, 140, 200, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(employeeLoginUpperJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1337, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(employeeLoginUpperJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 941, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
           // TODO add your handling code here:
        String username = usernameTxtField.getText();
        String password = passwordTxtField.getText();
        
        if (username.contains("admin") && password.contains("pass")) {
           JOptionPane.showMessageDialog(null, "Login successful!");
           
           usernameTxtField.setText("");
           passwordTxtField.setText("");
           warningLbl.setText("");
           UpdateStock updateStock = new UpdateStock();
           updateStock.setVisible(true);
           
           close();
           
        }
        else {
            //JOptionPane.showMessageDialog(null, "Login failed!\nClick OK to try again", "Incorrect login", JOptionPane.ERROR_MESSAGE);
            warningLbl.setText("Login failed! Please try again.");
            usernameTxtField.setText("");
            passwordTxtField.setText("");
        }
        
        
    }//GEN-LAST:event_loginBtnActionPerformed

    private void usernameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTxtFieldActionPerformed
        // TODO add your handling code here:
        usernameTxtField.setText("");
    }//GEN-LAST:event_usernameTxtFieldActionPerformed

    private void passwordTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtFieldActionPerformed
        // TODO add your handling code here:
        passwordTxtField.setText("");
    }//GEN-LAST:event_passwordTxtFieldActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Master1 master = new Master1();
        master.setVisible(true);
        
    }//GEN-LAST:event_exitBtnActionPerformed

    private void usernameTxtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameTxtFieldMouseClicked
        // TODO add your handling code here:
        usernameTxtField.setText(null);
    }//GEN-LAST:event_usernameTxtFieldMouseClicked

    private void passwordTxtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordTxtFieldMouseClicked
        // TODO add your handling code here:
        passwordTxtField.setText(null);
    }//GEN-LAST:event_passwordTxtFieldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoLbl;
    private javax.swing.JPanel employeeLoginLowerJPanel;
    private javax.swing.JPanel employeeLoginUpperJPanel;
    private javax.swing.JLabel employeeTxtLbl;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel loginTxtLbl;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JPasswordField passwordTxtField;
    private javax.swing.JLabel stockTxtLbl;
    private javax.swing.JLabel updateTxtLbl;
    private javax.swing.JLabel usernameLbl;
    private javax.swing.JTextField usernameTxtField;
    private javax.swing.JLabel warningLbl;
    // End of variables declaration//GEN-END:variables

private void close() {
    this.setVisible(false);
    //Master master = new Master();
        //master.setVisible(true);
        
        
    //WindowEvent winClose = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    //Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClose);
    
    
}


}
