/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stock;

import java.util.Arrays;
import javax.swing.table.*;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author jenz_
 */
public class UpdateStock extends javax.swing.JFrame {

    /**
     * Creates new form UpdateStock
     */
    public UpdateStock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateStockMiddleJPanel = new javax.swing.JPanel();
        stockTxtLbl = new javax.swing.JLabel();
        updateTxtLbl = new javax.swing.JLabel();
        logoTxtLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        updateStockUpperJPanel = new javax.swing.JPanel();
        addStockItemBtn = new javax.swing.JButton();
        editStockItemBtn = new javax.swing.JButton();
        updateStockMenuBar = new javax.swing.JMenuBar();
        fileMenuBtn = new javax.swing.JMenu();
        addStockMenuItem = new javax.swing.JMenuItem();
        editStockMenuItem = new javax.swing.JMenuItem();
        changeUserMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenuBtn = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gmarket");
        setIconImage(new ImageIcon(getClass().getResource("icon.gif")).getImage());

        updateStockMiddleJPanel.setBackground(new java.awt.Color(0, 153, 255));
        updateStockMiddleJPanel.setLayout(null);

        stockTxtLbl.setFont(new java.awt.Font("Harlow Solid Italic", 1, 48)); // NOI18N
        stockTxtLbl.setText(" Logistics");
        updateStockMiddleJPanel.add(stockTxtLbl);
        stockTxtLbl.setBounds(310, 660, 230, 85);

        updateTxtLbl.setFont(new java.awt.Font("Harlow Solid Italic", 1, 48)); // NOI18N
        updateTxtLbl.setText("Warehouse &");
        updateStockMiddleJPanel.add(updateTxtLbl);
        updateTxtLbl.setBounds(240, 600, 310, 85);

        logoTxtLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/img/fork2resized.png"))); // NOI18N
        updateStockMiddleJPanel.add(logoTxtLbl);
        logoTxtLbl.setBounds(430, 510, 270, 271);

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Category", "Price", "Quantity"
            }
        ));
        DefaultTableModel model = (DefaultTableModel) tblProduct.getModel();
        model.addRow(new Object[]{"Gorilla Suit","Clothing & Footwear","35", "5"});
        tblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduct);

        updateStockMiddleJPanel.add(jScrollPane1);
        jScrollPane1.setBounds(100, 70, 1080, 410);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/img/Gmarket_2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        updateStockMiddleJPanel.add(jPanel1);
        jPanel1.setBounds(830, 560, 460, 230);

        label1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        label1.setText("HELLO ADMIN");
        updateStockMiddleJPanel.add(label1);
        label1.setBounds(10, 0, 110, 30);

        label2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        label2.setText("LOGOUT");
        label2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label2MouseClicked(evt);
            }
        });
        updateStockMiddleJPanel.add(label2);
        label2.setBounds(1210, 0, 80, 40);

        updateStockUpperJPanel.setBackground(new java.awt.Color(0, 0, 0));

        addStockItemBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/img/Add_Row.png"))); // NOI18N
        addStockItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStockItemBtnActionPerformed(evt);
            }
        });

        editStockItemBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/img/edit_item.png"))); // NOI18N
        editStockItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStockItemBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updateStockUpperJPanelLayout = new javax.swing.GroupLayout(updateStockUpperJPanel);
        updateStockUpperJPanel.setLayout(updateStockUpperJPanelLayout);
        updateStockUpperJPanelLayout.setHorizontalGroup(
            updateStockUpperJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateStockUpperJPanelLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(addStockItemBtn)
                .addGap(36, 36, 36)
                .addComponent(editStockItemBtn)
                .addContainerGap(951, Short.MAX_VALUE))
        );
        updateStockUpperJPanelLayout.setVerticalGroup(
            updateStockUpperJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateStockUpperJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(updateStockUpperJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editStockItemBtn)
                    .addComponent(addStockItemBtn))
                .addContainerGap())
        );

        fileMenuBtn.setText("File");

        addStockMenuItem.setText("Add Stock...");
        addStockMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStockMenuItemActionPerformed(evt);
            }
        });
        fileMenuBtn.add(addStockMenuItem);

        editStockMenuItem.setText("Update Existing Stock...");
        editStockMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStockMenuItemActionPerformed(evt);
            }
        });
        fileMenuBtn.add(editStockMenuItem);

        changeUserMenuItem.setText("Change User...");
        changeUserMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeUserMenuItemActionPerformed(evt);
            }
        });
        fileMenuBtn.add(changeUserMenuItem);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenuBtn.add(exitMenuItem);

        updateStockMenuBar.add(fileMenuBtn);

        editMenuBtn.setText("Edit");
        updateStockMenuBar.add(editMenuBtn);

        setJMenuBar(updateStockMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateStockMiddleJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(updateStockUpperJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(updateStockUpperJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateStockMiddleJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Master1 master = new Master1();
        master.setVisible(true);
        
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void changeUserMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeUserMenuItemActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        EmployeeLogin employeeLogin = new EmployeeLogin();
        employeeLogin.setVisible(true);
    }//GEN-LAST:event_changeUserMenuItemActionPerformed

    private void addStockItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStockItemBtnActionPerformed
        // TODO add your handling code here:
        AddStockItem addStockItem = new AddStockItem();
        addStockItem.setVisible(true);
    }//GEN-LAST:event_addStockItemBtnActionPerformed

    private void addStockMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStockMenuItemActionPerformed
        // TODO add your handling code here:
        AddStockItem addStockItem = new AddStockItem();
        addStockItem.setVisible(true);
    }//GEN-LAST:event_addStockMenuItemActionPerformed

    private void editStockItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStockItemBtnActionPerformed
        // TODO add your handling code here:
        EditStockItem editStockItem = new EditStockItem();
        editStockItem.setVisible(true);
    }//GEN-LAST:event_editStockItemBtnActionPerformed

    private void tblProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductMouseClicked
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) ProductTable.tblProduct.getModel();
        //tfProName.setText(model.getValueAt(tblProduct.getSelectedRow(), 0).toString());
        //cbCategory.setSelectedItem(model.getValueAt(tblProduct.getSelectedRow(), 1).toString());
        //tfPrice.setText(model.getValueAt(tblProduct.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_tblProductMouseClicked

    private void editStockMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStockMenuItemActionPerformed
        // TODO add your handling code here:
        EditStockItem editStockItem = new EditStockItem();
        editStockItem.setVisible(true);
    }//GEN-LAST:event_editStockMenuItemActionPerformed

    private void label2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        EmployeeLogin employeeLogin = new EmployeeLogin();
        employeeLogin.setVisible(true);
    }//GEN-LAST:event_label2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStockItemBtn;
    private javax.swing.JMenuItem addStockMenuItem;
    private javax.swing.JMenuItem changeUserMenuItem;
    private javax.swing.JMenu editMenuBtn;
    private javax.swing.JButton editStockItemBtn;
    private javax.swing.JMenuItem editStockMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenuBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JLabel logoTxtLbl;
    private javax.swing.JLabel stockTxtLbl;
    public static javax.swing.JTable tblProduct;
    private javax.swing.JMenuBar updateStockMenuBar;
    private javax.swing.JPanel updateStockMiddleJPanel;
    private javax.swing.JPanel updateStockUpperJPanel;
    private javax.swing.JLabel updateTxtLbl;
    // End of variables declaration//GEN-END:variables

}
